apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  profile:
    displayName: Guest User
    email: guest@example.com
    picture: https://avatars.dicebear.com/api/avataaars/guest@example.com.svg?background=%23fff
  memberOf:
  - default-team
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: jon
spec:
  profile:
    displayName: Jon
    email: jon@example.com
    picture: https://avatars.dicebear.com/api/bottts/user2.svg
  memberOf:
  - default-team
  - platform-team
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: cody
spec:
  profile:
    displayName: Cody
    email: cody@example.com
    picture: https://avatars.dicebear.com/api/avataaars/guest@example.com.svg?background=%23fff
  memberOf: 
  - default-team
